package com.example.movexa.data.model

import com.example.movexa.data.model.enums.AlertPriority
import com.example.movexa.data.model.enums.AlertStatus
import com.example.movexa.data.model.enums.AlertType

/**
 * Alert data model for fleet warnings, notifications, and automated alerts.
 *
 * Firestore collection: alerts/{alertId}
 */
data class Alert(
    val alertId: String = "",
    val type: AlertType = AlertType.GENERAL,
    val vehicleId: String? = null,
    val driverId: String? = null,
    val tripId: String? = null,
    val companyId: String = "",
    val priority: AlertPriority = AlertPriority.MEDIUM,
    val status: AlertStatus = AlertStatus.ACTIVE,
    val title: String = "",
    val message: String = "",
    val timestamp: Long = System.currentTimeMillis(),
    val location: GeoPoint? = null,
    val resolvedBy: String? = null,
    val resolvedAt: Long = 0L,
    val actionRequired: Boolean = false,
    val autoGenerated: Boolean = false,
    val metadata: Map<String, Any> = emptyMap()
) {
    /**
     * Whether this alert needs attention (active + urgent).
     */
    val needsImmediateAttention: Boolean
        get() = status.isOpen() && priority.isUrgent()

    fun toMap(): Map<String, Any?> {
        return mapOf(
            "alertId" to alertId,
            "type" to type.name,
            "vehicleId" to vehicleId,
            "driverId" to driverId,
            "tripId" to tripId,
            "companyId" to companyId,
            "priority" to priority.name,
            "status" to status.name,
            "title" to title,
            "message" to message,
            "timestamp" to timestamp,
            "location" to location?.toMap(),
            "resolvedBy" to resolvedBy,
            "resolvedAt" to resolvedAt,
            "actionRequired" to actionRequired,
            "autoGenerated" to autoGenerated,
            "metadata" to metadata
        )
    }

    companion object {
        const val COLLECTION_NAME = "alerts"

        @Suppress("UNCHECKED_CAST")
        fun fromMap(map: Map<String, Any?>): Alert {
            return Alert(
                alertId = map["alertId"] as? String ?: "",
                type = AlertType.fromString(map["type"] as? String),
                vehicleId = map["vehicleId"] as? String,
                driverId = map["driverId"] as? String,
                tripId = map["tripId"] as? String,
                companyId = map["companyId"] as? String ?: "",
                priority = AlertPriority.fromString(map["priority"] as? String),
                status = AlertStatus.fromString(map["status"] as? String),
                title = map["title"] as? String ?: "",
                message = map["message"] as? String ?: "",
                timestamp = (map["timestamp"] as? Number)?.toLong() ?: 0L,
                location = (map["location"] as? Map<String, Any?>)?.let {
                    GeoPoint.fromMap(it)
                },
                resolvedBy = map["resolvedBy"] as? String,
                resolvedAt = (map["resolvedAt"] as? Number)?.toLong() ?: 0L,
                actionRequired = map["actionRequired"] as? Boolean ?: false,
                autoGenerated = map["autoGenerated"] as? Boolean ?: false,
                metadata = (map["metadata"] as? Map<String, Any>) ?: emptyMap()
            )
        }
    }
}
