package com.example.movexa.ui.dashboard.driver

import android.animation.ObjectAnimator
import android.view.View
import android.view.animation.DecelerateInterpolator
import androidx.core.content.ContextCompat
import androidx.fragment.app.viewModels
import androidx.recyclerview.widget.LinearLayoutManager
import com.example.movexa.R
import com.example.movexa.data.model.DriverSummary
import com.example.movexa.databinding.FragmentDriverPerformanceBinding
import com.example.movexa.service.DriverScoringEngine
import com.example.movexa.ui.base.BaseFragment

/**
 * Driver Performance screen — displays the driver's safety score,
 * driving statistics, violation breakdown, and improvement suggestions.
 *
 * ═══════════════════════════════════════════════════════════════
 * SECTIONS
 * ═══════════════════════════════════════════════════════════════
 *
 * 1. **Score Card** — animated circular progress with grade badge
 *    and trend indicator (Improving / Declining / Stable).
 *
 * 2. **Statistics Grid** — 4 cards showing completed trips, total
 *    distance, driving hours, and average fuel mileage.
 *
 * 3. **Score Breakdown** — base score, total penalties, trip
 *    completion bonus, and fuel efficiency bonus.
 *
 * 4. **Violations** — RecyclerView of violation types with count
 *    and penalty points. Only shows types with count > 0.
 *
 * 5. **Suggestions** — RecyclerView of dynamic tips generated by
 *    [DriverScoringEngine] based on violation patterns.
 *
 * ═══════════════════════════════════════════════════════════════
 * STATES
 * ═══════════════════════════════════════════════════════════════
 *
 * - **Loading** — spinner while score is being calculated
 * - **Content** — full performance dashboard
 * - **Empty** — friendly message when no trips yet
 * - **Error** — error message with retry button
 *
 * Pull-to-refresh triggers a full score recalculation.
 */
class DriverPerformanceFragment : BaseFragment<FragmentDriverPerformanceBinding>(
    FragmentDriverPerformanceBinding::inflate
) {

    // ─── ViewModel ──────────────────────────────────────────────
    private val viewModel: DriverPerformanceViewModel by viewModels()

    // ─── Adapters ───────────────────────────────────────────────
    private lateinit var violationAdapter: ViolationListAdapter
    private lateinit var suggestionAdapter: SuggestionListAdapter

    // ─── Animation ──────────────────────────────────────────────
    private var scoreAnimator: ObjectAnimator? = null

    // ═══════════════════════════════════════════════════════════
    //  INIT VIEWS
    // ═══════════════════════════════════════════════════════════

    override fun initViews() {
        setupRecyclerViews()
        viewModel.initialize()
    }

    /**
     * Set up the violation and suggestion RecyclerViews.
     */
    private fun setupRecyclerViews() {
        // Violations
        violationAdapter = ViolationListAdapter()
        binding.rvViolations.apply {
            layoutManager = LinearLayoutManager(requireContext())
            adapter = violationAdapter
            isNestedScrollingEnabled = false
        }

        // Suggestions
        suggestionAdapter = SuggestionListAdapter()
        binding.rvSuggestions.apply {
            layoutManager = LinearLayoutManager(requireContext())
            adapter = suggestionAdapter
            isNestedScrollingEnabled = false
        }
    }

    // ═══════════════════════════════════════════════════════════
    //  SETUP LISTENERS
    // ═══════════════════════════════════════════════════════════

    override fun setupListeners() {
        // Pull-to-refresh
        binding.swipeRefresh.setOnRefreshListener {
            viewModel.refreshScore()
        }
        binding.swipeRefresh.setColorSchemeResources(
            R.color.primary,
            R.color.secondary,
            R.color.score_excellent
        )

        // Retry button
        binding.btnRetry.setOnClickListener {
            viewModel.refreshScore()
        }
    }

    // ═══════════════════════════════════════════════════════════
    //  OBSERVE DATA
    // ═══════════════════════════════════════════════════════════

    override fun observeData() {
        // Screen state
        collectLatestFlow(viewModel.screenState) { state ->
            updateScreenState(state)
        }

        // Summary data
        collectLatestFlow(viewModel.summary) { summary ->
            summary?.let { updateScoreCard(it) }
            summary?.let { updateStatistics(it) }
            summary?.let { updateBreakdown(it) }
        }

        // Violations list
        collectLatestFlow(viewModel.violations) { violations ->
            violationAdapter.submitList(violations)
            updateViolationsHeader(violations)
        }

        // Suggestions list
        collectLatestFlow(viewModel.suggestions) { suggestions ->
            suggestionAdapter.submitList(suggestions)
        }

        // Refreshing state (SwipeRefreshLayout)
        collectLatestFlow(viewModel.isRefreshing) { refreshing ->
            binding.swipeRefresh.isRefreshing = refreshing
        }

        // Error events
        collectFlow(viewModel.errorEvent) { message ->
            showError(message)
        }

        // Success events
        collectFlow(viewModel.successEvent) { message ->
            showSuccess(message)
        }
    }

    // ═══════════════════════════════════════════════════════════
    //  SCREEN STATE
    // ═══════════════════════════════════════════════════════════

    /**
     * Show/hide the appropriate state container.
     */
    private fun updateScreenState(state: DriverPerformanceViewModel.ScreenState) {
        binding.layoutLoading.visibility = View.GONE
        binding.layoutError.visibility = View.GONE
        binding.layoutEmpty.visibility = View.GONE
        binding.swipeRefresh.visibility = View.GONE

        when (state) {
            is DriverPerformanceViewModel.ScreenState.Loading -> {
                binding.layoutLoading.visibility = View.VISIBLE
            }
            is DriverPerformanceViewModel.ScreenState.Content -> {
                binding.swipeRefresh.visibility = View.VISIBLE
            }
            is DriverPerformanceViewModel.ScreenState.Empty -> {
                binding.layoutEmpty.visibility = View.VISIBLE
            }
            is DriverPerformanceViewModel.ScreenState.Error -> {
                binding.layoutError.visibility = View.VISIBLE
            }
        }
    }

    // ═══════════════════════════════════════════════════════════
    //  SCORE CARD
    // ═══════════════════════════════════════════════════════════

    /**
     * Update the score circle, grade badge, trend badge, and
     * last-updated label from the driver summary.
     */
    private fun updateScoreCard(summary: DriverSummary) {
        // ── Animated Score Ring ──────────────────────────────────
        animateScoreRing(summary.score)

        // ── Score Value ─────────────────────────────────────────
        binding.tvScoreValue.text = summary.score.toString()

        // ── Ring Color ──────────────────────────────────────────
        val ringColor = getGradeRingColor(summary.grade)
        binding.progressScore.setIndicatorColor(
            ContextCompat.getColor(requireContext(), ringColor)
        )

        // ── Grade Badge ─────────────────────────────────────────
        val gradeText = getGradeDisplayText(summary.grade)
        binding.tvGradeBadge.text = getString(R.string.perf_grade_badge, gradeText)
        val gradeBgColor = getGradeBgColor(summary.grade)
        val gradeTextColor = getGradeTextColor(summary.grade)
        binding.tvGradeBadge.setTextColor(
            ContextCompat.getColor(requireContext(), gradeTextColor)
        )
        binding.tvGradeBadge.background?.setTint(
            ContextCompat.getColor(requireContext(), gradeBgColor)
        )

        // ── Trend Badge ─────────────────────────────────────────
        val (trendText, trendTextColor, trendBgColor) = getTrendVisuals(summary.trend)
        binding.tvTrendBadge.text = trendText
        binding.tvTrendBadge.setTextColor(
            ContextCompat.getColor(requireContext(), trendTextColor)
        )
        binding.tvTrendBadge.background?.setTint(
            ContextCompat.getColor(requireContext(), trendBgColor)
        )

        // ── Last Updated ────────────────────────────────────────
        val timeAgo = formatTimeAgo(summary.lastUpdated)
        binding.tvLastUpdated.text = getString(R.string.perf_last_updated, timeAgo)
    }

    /**
     * Animate the circular progress indicator from 0 to the score.
     */
    private fun animateScoreRing(score: Int) {
        scoreAnimator?.cancel()
        scoreAnimator = ObjectAnimator.ofInt(
            binding.progressScore,
            "progress",
            0,
            score
        ).apply {
            duration = 1200
            interpolator = DecelerateInterpolator(1.5f)
            start()
        }
    }

    // ═══════════════════════════════════════════════════════════
    //  STATISTICS
    // ═══════════════════════════════════════════════════════════

    /**
     * Update the 4 statistics cards.
     */
    private fun updateStatistics(summary: DriverSummary) {
        binding.tvStatTripsValue.text = summary.completedTrips.toString()
        binding.tvStatDistanceValue.text = summary.distanceDisplay
        binding.tvStatHoursValue.text = summary.drivingHoursDisplay
        binding.tvStatMileageValue.text = summary.mileageDisplay
    }

    // ═══════════════════════════════════════════════════════════
    //  SCORE BREAKDOWN
    // ═══════════════════════════════════════════════════════════

    /**
     * Update the breakdown card with base score, penalties, and bonuses.
     */
    private fun updateBreakdown(summary: DriverSummary) {
        binding.tvBreakdownBase.text = getString(
            R.string.perf_breakdown_base_format, 100
        )

        if (summary.totalPenalties > 0) {
            binding.tvBreakdownPenalties.text = getString(
                R.string.perf_breakdown_penalty_format, summary.totalPenalties
            )
        } else {
            binding.tvBreakdownPenalties.text = getString(
                R.string.perf_breakdown_base_format, 0
            )
            binding.tvBreakdownPenalties.setTextColor(
                ContextCompat.getColor(requireContext(), R.color.text_secondary)
            )
        }

        if (summary.tripCompletionBonus > 0) {
            binding.tvBreakdownTripBonus.text = getString(
                R.string.perf_breakdown_bonus_format, summary.tripCompletionBonus
            )
        } else {
            binding.tvBreakdownTripBonus.text = getString(
                R.string.perf_breakdown_base_format, 0
            )
            binding.tvBreakdownTripBonus.setTextColor(
                ContextCompat.getColor(requireContext(), R.color.text_secondary)
            )
        }

        if (summary.fuelEfficiencyBonus > 0) {
            binding.tvBreakdownFuelBonus.text = getString(
                R.string.perf_breakdown_bonus_format, summary.fuelEfficiencyBonus
            )
        } else {
            binding.tvBreakdownFuelBonus.text = getString(
                R.string.perf_breakdown_base_format, 0
            )
            binding.tvBreakdownFuelBonus.setTextColor(
                ContextCompat.getColor(requireContext(), R.color.text_secondary)
            )
        }
    }

    // ═══════════════════════════════════════════════════════════
    //  VIOLATIONS HEADER
    // ═══════════════════════════════════════════════════════════

    /**
     * Update the violations section header and empty state.
     */
    private fun updateViolationsHeader(
        violations: List<DriverPerformanceViewModel.ViolationItem>
    ) {
        if (violations.isEmpty()) {
            binding.tvNoViolations.visibility = View.VISIBLE
            binding.rvViolations.visibility = View.GONE
            binding.tvViolationsCount.text = ""
        } else {
            binding.tvNoViolations.visibility = View.GONE
            binding.rvViolations.visibility = View.VISIBLE
            val totalEvents = violations.sumOf { it.count }
            binding.tvViolationsCount.text = getString(
                R.string.perf_violations_subtitle, totalEvents
            )
        }
    }

    // ═══════════════════════════════════════════════════════════
    //  VISUAL HELPERS
    // ═══════════════════════════════════════════════════════════

    /**
     * Get the ring color for the score circle based on grade.
     */
    private fun getGradeRingColor(grade: String): Int {
        return when (grade) {
            "Excellent" -> R.color.score_excellent_ring
            "Good" -> R.color.score_good_ring
            "Average" -> R.color.score_average_ring
            else -> R.color.score_risky_ring
        }
    }

    /**
     * Get the display text for a grade.
     */
    private fun getGradeDisplayText(grade: String): String {
        return when (grade) {
            "Excellent" -> getString(R.string.perf_grade_excellent)
            "Good" -> getString(R.string.perf_grade_good)
            "Average" -> getString(R.string.perf_grade_average)
            else -> getString(R.string.perf_grade_risky)
        }
    }

    /**
     * Get the background color for the grade badge.
     */
    private fun getGradeBgColor(grade: String): Int {
        return when (grade) {
            "Excellent" -> R.color.score_excellent_bg
            "Good" -> R.color.score_good_bg
            "Average" -> R.color.score_average_bg
            else -> R.color.score_risky_bg
        }
    }

    /**
     * Get the text color for the grade badge.
     */
    private fun getGradeTextColor(grade: String): Int {
        return when (grade) {
            "Excellent" -> R.color.score_excellent
            "Good" -> R.color.score_good
            "Average" -> R.color.score_average
            else -> R.color.score_risky
        }
    }

    /**
     * Get the text, text color, and background color for the trend badge.
     */
    private fun getTrendVisuals(
        trend: DriverSummary.ScoreTrend
    ): Triple<String, Int, Int> {
        return when (trend) {
            DriverSummary.ScoreTrend.UP -> Triple(
                getString(R.string.perf_trend_up),
                R.color.score_trend_up,
                R.color.score_trend_up_bg
            )
            DriverSummary.ScoreTrend.DOWN -> Triple(
                getString(R.string.perf_trend_down),
                R.color.score_trend_down,
                R.color.score_trend_down_bg
            )
            DriverSummary.ScoreTrend.STABLE -> Triple(
                getString(R.string.perf_trend_stable),
                R.color.score_trend_stable,
                R.color.score_trend_stable_bg
            )
        }
    }

    /**
     * Format a timestamp into a human-readable "time ago" string.
     */
    private fun formatTimeAgo(timestamp: Long): String {
        val now = System.currentTimeMillis()
        val diff = now - timestamp

        val minutes = diff / 60_000
        val hours = diff / 3_600_000
        val days = diff / 86_400_000

        return when {
            minutes < 1 -> "just now"
            minutes < 60 -> "${minutes}m ago"
            hours < 24 -> "${hours}h ago"
            days < 7 -> "${days}d ago"
            else -> "${days / 7}w ago"
        }
    }

    // ═══════════════════════════════════════════════════════════
    //  CLEANUP
    // ═══════════════════════════════════════════════════════════

    override fun onDestroyView() {
        scoreAnimator?.cancel()
        scoreAnimator = null
        super.onDestroyView()
    }
}
