package com.example.movexa.data.model.enums

/**
 * Types of alerts generated by the fleet management system.
 */
enum class AlertType(val displayName: String) {
    // Vehicle alerts
    VEHICLE_BREAKDOWN("Vehicle Breakdown"),
    SERVICE_DUE("Service Due"),
    DOCUMENT_EXPIRY("Document Expiry"),
    LOW_FUEL("Low Fuel"),
    OVER_SPEED("Over Speed"),

    // Driver alerts
    LICENSE_EXPIRY("License Expiry"),
    DRIVER_SOS("Driver SOS"),
    FATIGUE_WARNING("Fatigue Warning"),

    // Trip alerts
    ROUTE_DEVIATION("Route Deviation"),
    TRIP_DELAY("Trip Delay"),
    GEOFENCE_VIOLATION("Geofence Violation"),

    // System alerts
    SYSTEM_UPDATE("System Update"),
    CONNECTIVITY_LOST("Connectivity Lost"),
    GENERAL("General");

    companion object {
        fun fromString(value: String?): AlertType {
            return entries.firstOrNull {
                it.name.equals(value, ignoreCase = true)
            } ?: GENERAL
        }
    }
}
