package com.example.movexa.data.model.enums

/**
 * Types of alerts generated by the fleet management system.
 *
 * Categories:
 * - Vehicle alerts: Mechanical / document / fuel issues
 * - Driver behavior alerts: Generated by [BehaviorAnalysisEngine]
 * - Trip alerts: Route deviation, delays
 * - System alerts: Connectivity, updates
 */
enum class AlertType(val displayName: String, val isBehavioral: Boolean = false) {
    // ── Vehicle alerts ──────────────────────────────────────────
    VEHICLE_BREAKDOWN("Vehicle Breakdown"),
    SERVICE_DUE("Service Due"),
    DOCUMENT_EXPIRY("Document Expiry"),
    LOW_FUEL("Low Fuel"),
    OVER_SPEED("Over Speed", isBehavioral = true),

    // ── Driver behavior alerts (generated by BehaviorAnalysisEngine) ─
    HARSH_BRAKING("Harsh Braking", isBehavioral = true),
    HARSH_ACCELERATION("Harsh Acceleration", isBehavioral = true),
    LONG_IDLE("Long Idle", isBehavioral = true),
    ACCIDENT_SUSPECTED("Accident Suspected", isBehavioral = true),

    // ── Driver safety alerts ────────────────────────────────────
    LICENSE_EXPIRY("License Expiry"),
    DRIVER_SOS("Driver SOS"),
    FATIGUE_WARNING("Fatigue Warning"),

    // ── Trip alerts ─────────────────────────────────────────────
    ROUTE_DEVIATION("Route Deviation", isBehavioral = true),
    TRIP_DELAY("Trip Delay"),
    GEOFENCE_VIOLATION("Geofence Violation"),

    // ── System alerts ───────────────────────────────────────────
    SYSTEM_UPDATE("System Update"),
    CONNECTIVITY_LOST("Connectivity Lost"),
    GENERAL("General");

    companion object {
        fun fromString(value: String?): AlertType {
            return entries.firstOrNull {
                it.name.equals(value, ignoreCase = true)
            } ?: GENERAL
        }

        /**
         * Returns only alert types that are generated by the behavior analysis engine.
         */
        fun behavioralTypes(): List<AlertType> = entries.filter { it.isBehavioral }
    }
}
